name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  build_and_deploy:
    if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message), '#build') }}
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: pwd
      - run: npm i yarn
      - name: Create Client Build
        working-directory: ./client
        run: |
          pwd
          yarn install
          yarn build
      - name: Create Server Build
        working-directory: ./server
        run: |
          pwd
          yarn install
          yarn build
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "angelxv-thullo" #Must be unique in Heroku
          heroku_email: "angeloxv@outlook.it"
          rollbackonhealthcheckfailed: true
